In [1]:
#numpy

#Used to handle high dimensional data 

#when objects are initiated?

#objects are instantiated only when we do value assignment

x = [1,2,3] #x is object here
print(id(x))

2742795968960


In [3]:
import sys
!conda install --yes --prefix {sys.prefix} numpy

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\STSC.LENOVO-131292\anaconda3\envs\rstudio

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2021.10.26 |       haa95532_4         116 KB
    numpy-1.21.2               |   py39hfca59bb_0          24 KB
    numpy-base-1.21.2          |   py39h0829f74_0         4.4 MB
    ------------------------------------------------------------
                                           Total:         4.6 MB

The following NEW packages will be INSTALLED:

  blas               pkgs/main/win-64::blas-1.0-mkl
  intel-openmp       pkgs/main/win-64::intel-openmp-2021.4.0-haa95532_3556
  mkl                pkgs/main/win-64::mkl-2021.4.0-haa95532_640
  mkl-service        pkgs/main/win-64::mkl-service-2.4.0-py39h2bbff1b_0
  mkl_fft            pkgs/main/win-64::mkl_



==> WARNING: A newer version of conda exists. <==
  current version: 4.10.3
  latest version: 4.11.0

Please update conda by running

    $ conda update -n base -c defaults conda




In [22]:
import numpy as np

arr_ex = np.array([1,2,3])
print(arr_ex)

arr = np.array([[1,2,3],
               [3,2,1]])
print(arr)

print(arr.shape) # shape of the matrix
print(arr.shape[0])
print(arr.shape[1])
print('-----------------------------------------------------------------')

zeros = np.zeros(arr.shape)
print(zeros)
print('-----------------------------------------------------------------')

#identity matrix

id_matrix = np.eye(3)
print(id_matrix)
print('-----------------------------------------------------------------')

#element wise calculation

arrr = arr
print(arrr)
print(arrr ** 2) 
print('-----------------------------------------------------------------')

#broadcasting - frist bring two array into same shape then do the elementwise calculation

print(arrr + 1) #<- broadcasting
print('-----------------------------------------------------------------')

arr1 = np.array([1,2]) # rank 1 array
print(arr1)

arr2 = arr1.reshape((1,2))
print(arr2)

arr3 = arr1.reshape((2,1))
print(arr3)

[1 2 3]
[[1 2 3]
 [3 2 1]]
(2, 3)
2
3
-----------------------------------------------------------------
[[0. 0. 0.]
 [0. 0. 0.]]
-----------------------------------------------------------------
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
-----------------------------------------------------------------
[[1 2 3]
 [3 2 1]]
[[1 4 9]
 [9 4 1]]
-----------------------------------------------------------------
[[2 3 4]
 [4 3 2]]
-----------------------------------------------------------------
[1 2]
[[1 2]]
[[1]
 [2]]


In [29]:
#higher dimension

arr = np.array([[[1,2,3],
               [3,2,1]],
               
              [[4,5,6],
              [6,5,4]],
               
              [[7,8,9],
              [9,8,7]]])

print(arr.shape)
print(arr)
print('-----------------------------------------------------------------')

#only want the first and third column
print(arr[:,:,(0,2)])
print('-----------------------------------------------------------------')

print(arr[:,0,(0,2)][:,np.newaxis,:]) #dropping the column

(3, 2, 3)
[[[1 2 3]
  [3 2 1]]

 [[4 5 6]
  [6 5 4]]

 [[7 8 9]
  [9 8 7]]]
-----------------------------------------------------------------
[[[1 3]
  [3 1]]

 [[4 6]
  [6 4]]

 [[7 9]
  [9 7]]]
-----------------------------------------------------------------
[[[1 3]]

 [[4 6]]

 [[7 9]]]


In [33]:
#transpose
arr = np.array([[1,2,3],
               [3,2,1]])
print(arr)
print(arr.shape,'is the shape of arr')
print('-----------------------------------------------------------------')

tran = arr.T
print(tran)
print(tran.shape,'is the shape of transpose matrix')

[[1 2 3]
 [3 2 1]]
(2, 3) is the shape of arr
-----------------------------------------------------------------
[[1 3]
 [2 2]
 [3 1]]
(3, 2) is the shape of transpose matrix


In [41]:
#matmul, used in the calculation vectorization. matrix multiplication

arr = np.array([[1,2,3],
               [3,2,1]])
print(arr)
print('-----------------------------------------------------------------')

arr1 = np.array(range(6)).reshape((3,2))
print(arr1)
print('-----------------------------------------------------------------')

print(np.matmul(arr,arr1))
print('-----------------------------------------------------------------')

print(arr@arr1)

[[1 2 3]
 [3 2 1]]
-----------------------------------------------------------------
[[0 1]
 [2 3]
 [4 5]]
-----------------------------------------------------------------
[[16 22]
 [ 8 14]]
-----------------------------------------------------------------
[[16 22]
 [ 8 14]]


In [46]:
#flatten the array i.e to the rank 1 array

arr = np.array([[[1,2,3],
               [3,2,1]],
               
              [[4,5,6],
              [6,5,4]],
               
              [[7,8,9],
              [9,8,7]]])

print(arr.flatten())
print(arr.reshape(-1))
print(arr.reshape(3,-1,6)) #remove the row dimension

print(arr.reshape(3,6,-1))

[1 2 3 3 2 1 4 5 6 6 5 4 7 8 9 9 8 7]
[1 2 3 3 2 1 4 5 6 6 5 4 7 8 9 9 8 7]
[[[1 2 3 3 2 1]]

 [[4 5 6 6 5 4]]

 [[7 8 9 9 8 7]]]
[[[1]
  [2]
  [3]
  [3]
  [2]
  [1]]

 [[4]
  [5]
  [6]
  [6]
  [5]
  [4]]

 [[7]
  [8]
  [9]
  [9]
  [8]
  [7]]]


In [57]:
print(np.max(arr))
print('-----------------------------------------------------------------')

print(np.max(arr, axis=1))
print('-----------------------------------------------------------------')

print(np.max(arr, axis=1, keepdims=True)) #keeps the dimensions same if any dimension has 0
print('-----------------------------------------------------------------')

arr = np.array([[[1,2,3],
               [3,2,1]],
               
              [[4,5,6],
              [6,5,4]],
               
              [[0,1,0],
              [1,0,1]]])
print(np.max(arr, axis=1, keepdims=True))
print(np.max(arr, axis=1, keepdims=False))


6
-----------------------------------------------------------------
[[3 2 3]
 [6 5 6]
 [1 1 1]]
-----------------------------------------------------------------
[[[3 2 3]]

 [[6 5 6]]

 [[1 1 1]]]
-----------------------------------------------------------------
[[[3 2 3]]

 [[6 5 6]]

 [[1 1 1]]]
[[3 2 3]
 [6 5 6]
 [1 1 1]]


In [58]:
#standardized axis

#listen from class from 2 hrs



[[[1 2 3]
  [3 2 1]]

 [[4 5 6]
  [6 5 4]]

 [[0 1 0]
  [1 0 1]]]


In [62]:
#slicing using np arrays (on-hot encoding)

arr = np.array([[[1,2,3],
               [3,2,1]],
               
              [[4,5,6],
              [6,5,4]],
               
              [[0,1,0],
              [1,0,1]]])

rowarr = np.array([0,0,1])
colarr = np.array([0,1,2])

print(arr[:,rowarr,colarr])
print('------------------------------------------------')

arr1 = np.array([[[1,2,3],
               [4,5,6]],
               
              [[4,5,6],
              [7,8,9]],
               
              [[0,1,0],
              [0,0,1]]])

print(arr1[:,rowarr,colarr])

[[1 2 1]
 [4 5 4]
 [0 1 1]]
------------------------------------------------
[[1 2 6]
 [4 5 9]
 [0 1 1]]


In [68]:
target = [0,1,4,2,3,3] #one-hot encoding

# [[1,0,0,0,0],
#  [0,1,0,0,0],
#  [0,0,0,0,1],
#  [0,0,1,0,0],
#  [0,0,0,1,0],
#  [0,0,0,1,0]]

a=len(target)

b=len(set(target))

c =set(target)
print(a,b,c)
print()

target_one_hot = np.eye(len(set(target)))[np.array(target),:]
print(target_one_hot)

6 5 {0, 1, 2, 3, 4}

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]]


In [77]:
#inner product
import time


arr1 = np.array([1,0,3,2,54,2,3,1,7,2,3,5,1,2,3,4,5,6,7,8])
arr2 = np.array([1,0,3,12,5,2,3,1,7,2,23,5,41,2,3,4,53,6,7,8])

tic = time.process_time()

ctr = 0
while ctr<=10000:
    res = 0
    for i in range(arr1.shape[0]):
        res+= arr1[i] * arr2[i]
    ctr+=1
    
toc = time.process_time()

print("the result is "+ str(res) + " run time:" + str(1000*(toc-tic)))

the result is 949 run time:265.625


In [78]:
#method: vectorization

tic = time.process_time()

ctr = 0
while ctr<=10000:
    res = sum(arr1*arr2)
    ctr+=1
    
toc = time.process_time()

print("the result is "+ str(res) + " run time:" + str(1000*(toc-tic)))


the result is 949 run time:62.5


In [84]:
#outer product
tic = time.process_time()

ctr = 0
while ctr<=10000:
    res = np.sum(np.outer(arr1,arr2))
    ctr+=1
    
toc = time.process_time()

print("the result is "+ str(res) + " run time:" + str(1000*(toc-tic)))

#what is difference between sum and np.sum?

the result is 22372 run time:93.75


In [81]:
#method: for loop

tic = time.process_time()

ctr = 0
while ctr<=10000:
    res = 0
    for i in range(arr1.shape[0]):
        for j in range(arr2.shape[0]):
            res += arr1[i] * arr2[j]
    ctr+=1
    
toc = time.process_time()

print("the result is "+ str(res) + " run time:" + str(1000*(toc-tic)))

the result is 22372 run time:5062.5


In [90]:
#axis swapping. Nothing but the transpose of higher dimensional array

print(arr)
print('--------------------------------------------------------------------')

print(np.swapaxes(arr,1,2))
print('--------------------------------------------------------------------')

print(np.swapaxes(arr,2,1))


[[[1 2 3]
  [3 2 1]]

 [[4 5 6]
  [6 5 4]]

 [[0 1 0]
  [1 0 1]]]
--------------------------------------------------------------------
[[[1 3]
  [2 2]
  [3 1]]

 [[4 6]
  [5 5]
  [6 4]]

 [[0 1]
  [1 0]
  [0 1]]]
--------------------------------------------------------------------
[[[1 3]
  [2 2]
  [3 1]]

 [[4 6]
  [5 5]
  [6 4]]

 [[0 1]
  [1 0]
  [0 1]]]


In [ ]:
RGB: three primary color
    (mxn) pixels on each color channel
    for each pixel we have a color intensity, 0-255 -> 8 bit number:
        

In [91]:
pip install pillow

Note: you may need to restart the kernel to use updated packages.


In [5]:
from PIL import Image
import numpy as np

img = np.asarray(Image.open('C:/Users/STSC.LENOVO-131292/BAN 601/Lenna.png').convert('RGB'))
print(img)
print(img.shape)



[[[226 137 125]
  [226 137 125]
  [223 137 133]
  ...
  [230 148 122]
  [221 130 110]
  [200  99  90]]

 [[226 137 125]
  [226 137 125]
  [223 137 133]
  ...
  [230 148 122]
  [221 130 110]
  [200  99  90]]

 [[226 137 125]
  [226 137 125]
  [223 137 133]
  ...
  [230 148 122]
  [221 130 110]
  [200  99  90]]

 ...

 [[ 84  18  60]
  [ 84  18  60]
  [ 92  27  58]
  ...
  [173  73  84]
  [172  68  76]
  [177  62  79]]

 [[ 82  22  57]
  [ 82  22  57]
  [ 96  32  62]
  ...
  [179  70  79]
  [181  71  81]
  [185  74  81]]

 [[ 82  22  57]
  [ 82  22  57]
  [ 96  32  62]
  ...
  [179  70  79]
  [181  71  81]
  [185  74  81]]]
(512, 512, 3)


In [8]:
#generate a colorful noise image

arr = np.random.randint(0,255,size=(500,500,3))
arr = arr.astype(np.uint8)
pilimg = Image.fromarray(arr)
pilimg.show()

In [10]:
img = np.asarray(Image.open('C:/Users/STSC.LENOVO-131292/BAN 601/Lenna.png').convert('RGB'))
r,g,b = img.copy(), img.copy(), img.copy()
r[:,:,(1,2)]=0
g[:,:,(0,2)]=0
b[:,:,(0,1)]=0
pilimg=Image.fromarray(b)
pilimg.show()

In [11]:
imgAll = np.concatenate((r,g,b),axis=1)
pilimg = Image.fromarray(imgAll)
pilimg.show()

In [ ]:
#filter1: make the image more blue

def makeBlue(b_factor,img):
    '''
    the lower the b_factor the bluer the image is
    '''
    
    r,g,b = img

In [13]:
#filter2 : blur the image
#very similar to a CNN pooling layer. ---- what is this??
#for each color channel, for each pixel, we replcae it with the average of its surrounding pixels

def makeBlur(b_factor, img):
    '''
    the more the b_factor more blur in the image
    '''
    
    size=img.shape
    for i in range(size[0]):
        for j in range(size[1]):
            for k in range(size[2]):
                avgPixel = np.average(img[max(i-b_factor,0):min(i+b_factor,size[0]),
                                          max(j-b_factor,0):min(j+b_factor,size[1]),
                                          k])
                                          
                img[i,j,k]=avgPixel
    pilimg = Image.fromarray(img)
    pilimg.show()
makeBlur(5,np.asarray(Image.open('C:/Users/STSC.LENOVO-131292/BAN 601/Lenna.png').convert('RGB')))                  

In [ ]:
pandas, dataframe, iterations